import * as Base from './base';

export const filters = {
  California: true,
  Florida: true,
  Minnesota: true,
  'New York': true,
  Washington: true,
};

export const idGroupings = [
  {
    label: 'Northeast',
    ids: [
      'Maine',
      'New Hampshire',
      'Vermont',
      'Massachusetts',
      'New York',
      'Rhode Island',
      'Connecticut',
      'New Jersey',
      'Pennsylvania',
    ],
  },
  {
    label: 'Midwest',
    ids: [
      'Ohio',
      'Michigan',
      'Indiana',
      'Illinois',
      'Wisconsin',
      'Minnesota',
      'North Dakota',
      'South Dakota',
      'Nebraska',
      'Iowa',
      'Kansas',
      'Missouri',
    ],
  },
  {
    label: 'Southeast',
    ids: [
      'Maryland',
      'Delaware',
      'District of Columbia',
      'West Virginia',
      'Virginia',
      'Kentucky',
      'Tennessee',
      'North Carolina',
      'South Carolina',
      'Georgia',
      'Florida',
      'Alabama',
      'Mississippi',
    ],
  },
  {
    label: 'South',
    ids: [
      'Arkansas',
      'Louisiana',
      'Oklahoma',
      'Texas',
    ],
  },
  {
    label: 'Mountain',
    ids: [
      'Montana',
      'Idaho',
      'Wyoming',
      'Nevada',
      'Utah',
      'Colorado',
      'Arizona',
      'New Mexico',
    ],
  },
  {
    label: 'West',
    ids: [
      'California',
      'Oregon',
      'Washington',
      'Alaska',
      'Hawaii',
    ],
  },
  {
    label: 'Other US Territories',
    ids: [
      'American Samoa',
      'Guam',
      'Northern Mariana Islands',
      'Puerto Rico',
      'Virgin Islands',
    ],
  },
];

export const abbreviations = {
  Alabama: 'AL',
  Alaska: 'AK',
  'American Samoa': 'AS',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  'District of Columbia': 'DC',
  Florida: 'FL',
  Georgia: 'GA',
  Guam: 'GU',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  'Northern Mariana Islands': 'OH',
  Ohio: 'OK',
  Oklahoma: 'OR',
  Oregon: 'PW',
  Pennsylvania: 'PA',
  'Puerto Rico': 'PR',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  'Virgin Islands': 'VI',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

export const { defaultChartId } = Base;
export const spec = Base.makeSpec('US');
